fix: checks-done step must succeed
The checks-done step must succeed before we expect this pipeline to be able to get merged

adapted from https://github.com/orgs/community/discussions/26822#discussioncomment-3305794

diff --git a/.github/workflows/default.yml b/.github/workflows/default.yml
--- a/.github/workflows/default.yml
+++ b/.github/workflows/default.yml
@@ -43,10 +43,22 @@ jobs:
       version: 0.0.0-test
 
   checks-done:
+    if: ${{ always() }}
     runs-on: ubuntu-latest
     steps:
       - name: 🎉 Checks done
-        run: echo "🎉 All tests were successful."
+        run: |
+          result-build-showcases="${{ needs.build-showcases.result }}"
+          result-build-outputs="${{ needs.build-outputs.result }}"
+          result-test-packages="${{ needs.test-packages.result }}"
+          result-build-power-apps="${{ needs.build-power-apps.result }}"
+          if [[ $result-build-showcases == "success" && $result-build-outputs == "success" && $result-test-packages == "success" && $result-build-power-apps == "success" ]]; then
+             echo "🎉 All tests were successful."
+            exit 0
+          else
+             echo "Some tests were failing."
+            exit 1
+          fi
     needs: [build-showcases, build-outputs, test-packages, build-power-apps]
 
   deploy:
